<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tasnim Ara Siddique and Tahana Akram">

<title>Are Horoscopes Just Vague Nonsense? (Spoiler: Yes.) – Tasnim Ara Siddique</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/profile-piccture.jpg" rel="icon" type="image/jpeg">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-f732d29b5a2b62f8feb4fd3fb6baf7f1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8373614d2459814cf43b3bafbfccb8ad.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Tasnim Ara Siddique</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../skills.html"> 
<span class="menu-text">Skills</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/YOUR-LINKEDIN"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/YOUR-GITHUB"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Project_3_Template.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Are Horoscopes Just Vague Nonsense? (Spoiler: Yes.)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tasnim Ara Siddique and Tahana Akram </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>Let me paint you a picture. It’s 8 AM. You’re barely conscious, coffee in hand, and you open your horoscope app. It tells you: “Today is a powerful day for reflection. Your energy is shifting. Trust the process.” You nod slowly. Wow. It really gets you. Meanwhile, your friend, a Scorpio, deeply intense, obviously opens their horoscope. It says: “Today is a powerful day for reflection. Your energy is shifting. Trust the process.” Coincidence? So we had to ask, are horoscopes actually saying something real, or are they just really good at sounding deep while saying absolutely nothing? The stars had some explaining to do. Stay tuned to find out if the universe actually knows you or if it’s been bluffing this whole time.</p>
<p>Using a dataset of 21,959 daily horoscope predictions spanning all 12 zodiac signs, we applied text mining tools like tokenization, sentiment analysis, TF-IDF, and regular expressions to answer one very scientific question: are horoscopes actually different from each other, or is astrology just one giant copy-paste job with different star sign labels slapped on top? What we found might not shock the skeptics. But it might just convince your horoscope-obsessed roommate.</p>
<section id="the-data" class="level3">
<h3 class="anchored" data-anchor-id="the-data">The Data:</h3>
<p>Our dataset comes from Horoscopes.com, scraped and made available on Kaggle.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>horoscopes_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"horoscope_saved.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(horoscopes_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 21,959
Columns: 4
$ sign      &lt;chr&gt; "aries", "aries", "aries", "aries", "aries", "aries", "aries…
$ category  &lt;chr&gt; "general", "general", "general", "general", "general", "gene…
$ date      &lt;dbl&gt; 20200617, 20200618, 20200619, 20200620, 20200621, 20200622, …
$ horoscope &lt;chr&gt; "There's a great day ahead of you, Aries. You'll be blessed …</code></pre>
</div>
</div>
<p>It contains 21,959 daily horoscope predictions covering all 12 zodiac signs across a roughly two-year window. Each row represents one day’s prediction for one sign so every morning, all 12 signs got their personalized cosmic memo. Or, as we now suspect, their not-so-personalized cosmic memo. The raw data arrived with four columns: the zodiac sign (stored entirely in lowercase, because apparently the universe does not believe in capitalization), a category label, a date stored as a raw number like 20200617, and the horoscope text itself.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>horoscopes <span class="ot">&lt;-</span> horoscopes_raw <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">sign =</span> <span class="fu">str_to_title</span>(<span class="fu">str_trim</span>(sign)), <span class="co"># capitalize sign names</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">as.Date</span>(<span class="fu">as.character</span>(date), <span class="at">format =</span> <span class="st">"%Y%m%d"</span>) <span class="co"># convert raw numeric date to </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">#R Date</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sign <span class="sc">%in%</span> <span class="fu">c</span>(          <span class="co"># keep only valid zodiac signs</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Aries"</span>, <span class="st">"Taurus"</span>, <span class="st">"Gemini"</span>, <span class="st">"Cancer"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Leo"</span>, <span class="st">"Virgo"</span>, <span class="st">"Libra"</span>, <span class="st">"Scorpio"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sagittarius"</span>, <span class="st">"Capricorn"</span>, <span class="st">"Aquarius"</span>, <span class="st">"Pisces"</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(horoscope) <span class="sc">|&gt;</span>        <span class="co"># remove rows with missing text</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">month     =</span> <span class="fu">month</span>(date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_num =</span> <span class="fu">month</span>(date),</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">season    =</span> <span class="fu">case_when</span>(                     <span class="co"># assign meteorological season</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>      month_num <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">1</span>, <span class="dv">2</span>)  <span class="sc">~</span> <span class="st">"Winter"</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>      month_num <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)   <span class="sc">~</span> <span class="st">"Spring"</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>      month_num <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>)   <span class="sc">~</span> <span class="st">"Summer"</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>      month_num <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>) <span class="sc">~</span> <span class="st">"Fall"</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total horoscopes loaded:"</span>, <span class="fu">nrow</span>(horoscopes), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total horoscopes loaded: 21959 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Date range:"</span>, <span class="fu">format</span>(<span class="fu">min</span>(horoscopes<span class="sc">$</span>date)), <span class="st">"to"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">format</span>(<span class="fu">max</span>(horoscopes<span class="sc">$</span>date)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Date range: 2020-06-16 to 2021-06-16 </code></pre>
</div>
</div>
<p>Before any analysis, we had to clean things up, the data came in a bit rough around the edges. After all cleaning steps, all 21,959 horoscopes were retained with all 12 signs present and accounted for.</p>
<p>To make the analysis richer, we also built a zodiac metadata reference table from scratch a tidy little tibble containing each sign’s ruling planet, astrological element (Fire, Earth, Air, or Water), and modality (Cardinal, Fixed, or Mutable). We then joined this table onto our main dataset. This join turned out to be crucial later, because it let us test one of astrology’s most specific and testable claims: does your ruling planet actually show up more often in your horoscope than in everyone else’s? After all cleaning steps, all 21,959 horoscopes were retained, with all 12 signs present, we were ready to find out whether the cosmos had anything original to say.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a lookup table: each sign's ruling planet, element, modality, and plot color</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>zodiac_meta <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sign    =</span> <span class="fu">c</span>(<span class="st">"Aries"</span>,<span class="st">"Taurus"</span>,<span class="st">"Gemini"</span>,<span class="st">"Cancer"</span>,<span class="st">"Leo"</span>,<span class="st">"Virgo"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Libra"</span>,<span class="st">"Scorpio"</span>,<span class="st">"Sagittarius"</span>,<span class="st">"Capricorn"</span>,<span class="st">"Aquarius"</span>,<span class="st">"Pisces"</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ruling_planet =</span> <span class="fu">c</span>(<span class="st">"mars"</span>,<span class="st">"venus"</span>,<span class="st">"mercury"</span>,<span class="st">"moon"</span>,<span class="st">"sun"</span>,<span class="st">"mercury"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"venus"</span>,<span class="st">"pluto"</span>,<span class="st">"jupiter"</span>,<span class="st">"saturn"</span>,<span class="st">"uranus"</span>,<span class="st">"neptune"</span>),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">element  =</span> <span class="fu">c</span>(<span class="st">"Fire"</span>,<span class="st">"Earth"</span>,<span class="st">"Air"</span>,<span class="st">"Water"</span>,<span class="st">"Fire"</span>,<span class="st">"Earth"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Air"</span>,<span class="st">"Water"</span>,<span class="st">"Fire"</span>,<span class="st">"Earth"</span>,<span class="st">"Air"</span>,<span class="st">"Water"</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">modality =</span> <span class="fu">c</span>(<span class="st">"Cardinal"</span>,<span class="st">"Fixed"</span>,<span class="st">"Mutable"</span>,<span class="st">"Cardinal"</span>,<span class="st">"Fixed"</span>,<span class="st">"Mutable"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Cardinal"</span>,<span class="st">"Fixed"</span>,<span class="st">"Mutable"</span>,<span class="st">"Cardinal"</span>,<span class="st">"Fixed"</span>,<span class="st">"Mutable"</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">sign_color =</span> <span class="fu">c</span>(</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"#E24B4A"</span>,<span class="st">"#639922"</span>,<span class="st">"#EF9F27"</span>,<span class="st">"#85B7EB"</span>,<span class="st">"#D85A30"</span>,<span class="st">"#1D9E75"</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"#7F77DD"</span>,<span class="st">"#993556"</span>,<span class="st">"#BA7517"</span>,<span class="st">"#5F5E5A"</span>,<span class="st">"#378ADD"</span>,<span class="st">"#D4537E"</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Join metadata onto main horoscopes table so every row knows its element, planet, etc.</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>horoscopes <span class="ot">&lt;-</span> horoscopes <span class="sc">|&gt;</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(zodiac_meta, <span class="at">by =</span> <span class="st">"sign"</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify the join, should show all 12 signs with correct metadata</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>horoscopes <span class="sc">|&gt;</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(sign, ruling_planet, element, modality) <span class="sc">|&gt;</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(element, sign)<span class="sc">|&gt;</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Zodiac sign metadata joined to main dataset"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Zodiac sign metadata joined to main dataset</caption>
<thead>
<tr class="header">
<th style="text-align: left;">sign</th>
<th style="text-align: left;">ruling_planet</th>
<th style="text-align: left;">element</th>
<th style="text-align: left;">modality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">uranus</td>
<td style="text-align: left;">Air</td>
<td style="text-align: left;">Fixed</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: left;">Air</td>
<td style="text-align: left;">Mutable</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">venus</td>
<td style="text-align: left;">Air</td>
<td style="text-align: left;">Cardinal</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: left;">saturn</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: left;">Cardinal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taurus</td>
<td style="text-align: left;">venus</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: left;">Fixed</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: left;">Mutable</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">mars</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: left;">Cardinal</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leo</td>
<td style="text-align: left;">sun</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: left;">Fixed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: left;">jupiter</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: left;">Mutable</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cancer</td>
<td style="text-align: left;">moon</td>
<td style="text-align: left;">Water</td>
<td style="text-align: left;">Cardinal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pisces</td>
<td style="text-align: left;">neptune</td>
<td style="text-align: left;">Water</td>
<td style="text-align: left;">Mutable</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">pluto</td>
<td style="text-align: left;">Water</td>
<td style="text-align: left;">Fixed</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This join turned out to be crucial later, because it let us test one of astrology’s most specific and testable claims: does your ruling planet actually show up more often in your horoscope than in everyone else’s? The data was tidy, the metadata was joined, and we were ready to find out whether the cosmos had anything original to say.</p>
</section>
<section id="regex-do-the-stars-actually-talk-about-your-planet" class="level2">
<h2 class="anchored" data-anchor-id="regex-do-the-stars-actually-talk-about-your-planet">Regex: Do The Stars Actually Talk About Your Planet?</h2>
<p>If zodiac signs are supposed to have ruling planets, then we expected those planets to show up like proud parents at graduation. Mars should be cheering for Aries, Venus should be hyping up Taurus, and Mercury should be talking very fast in Gemini’s corner.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>planets_list <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sun"</span>,<span class="st">"moon"</span>,<span class="st">"mercury"</span>,<span class="st">"venus"</span>,<span class="st">"mars"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"jupiter"</span>,<span class="st">"saturn"</span>,<span class="st">"uranus"</span>,<span class="st">"neptune"</span>,<span class="st">"pluto"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>planet_pattern <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">b("</span>, <span class="fu">paste</span>(planets_list, <span class="at">collapse =</span> <span class="st">"|"</span>), <span class="st">")</span><span class="sc">\\</span><span class="st">b"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># \b word boundaries: "mars" won't match inside "smarts" or "remarkable"</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>planet_mentions <span class="ot">&lt;-</span> horoscopes <span class="sc">|&gt;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a> <span class="co"># lowercase for case-insensitive matching</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">text_lower =</span> <span class="fu">str_to_lower</span>(horoscope)) <span class="sc">|&gt;</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># extract all planet hits</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">planets_found =</span> <span class="fu">str_extract_all</span>(text_lower, planet_pattern)) <span class="sc">|&gt;</span>  </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># one row per planet mention</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(planets_found) <span class="sc">|&gt;</span> </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">planet_mentioned =</span> planets_found) <span class="sc">|&gt;</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># flag: is this the sign's own ruling planet?</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">is_ruling =</span> planet_mentioned <span class="sc">==</span> ruling_planet </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="co"># How often is each planet mentioned overall?</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>planet_freq <span class="ot">&lt;-</span> planet_mentions <span class="sc">|&gt;</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(planet_mentioned, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> <span class="fu">round</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>planet_freq <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Planet mention frequencies across all horoscopes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Planet mention frequencies across all horoscopes</caption>
<thead>
<tr class="header">
<th style="text-align: left;">planet_mentioned</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sun</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">43.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">moon</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">36.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">neptune</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">16.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">mars</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mercury</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">saturn</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The results were immediately revealing. Out of all planet mentions across the entire dataset, the sun accounted for 43.2% and the moon accounted for 36.5% together making up nearly 80% of all planetary references. Neptune came in third at 16.2%. Mars, Mercury, and Saturn each appeared just once, at 1.4% each. Venus, Jupiter, Uranus, and Pluto? Nowhere to be found. So, instead the sun and moon showed up to almost every party, while Venus, Jupiter, Uranus, and Pluto apparently forgot to RSVP. The universe may be vast, but these horoscopes are working with a very small guest list.</p>
<section id="does-your-ruling-planet-actually-show-up-in-your-horoscope" class="level3">
<h3 class="anchored" data-anchor-id="does-your-ruling-planet-actually-show-up-in-your-horoscope">Does Your Ruling Planet Actually Show Up in Your Horoscope?</h3>
<p>After finding out that the sun and moon were basically hogging the microphone, we had one more question: when the planets do get mentioned, is your own ruling planet actually getting VIP treatment, or is it stuck outside the club with Venus and Pluto? This is astrology’s core mechanical claim that your sign’s ruling planet actively shapes your daily cosmic experience. If astrology’s planetary system were working as advertised, you would expect each sign’s ruling planet to dominate its horoscope mentions ideally way above the 10% baseline you would get if all ten planets were mentioned equally at random. The results were not kind to astrology.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ruling_planet_summary <span class="ot">&lt;-</span> planet_mentions <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sign, ruling_planet) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_planet_mentions  =</span> <span class="fu">n</span>(),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ruling_planet_mentions =</span> <span class="fu">sum</span>(is_ruling),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_ruling =</span> <span class="fu">round</span>(ruling_planet_mentions <span class="sc">/</span> total_planet_mentions <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_ruling))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>ruling_planet_summary <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Ruling planet mention rate by zodiac sign"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Ruling planet mention rate by zodiac sign</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 26%">
<col style="width: 28%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">sign</th>
<th style="text-align: left;">ruling_planet</th>
<th style="text-align: right;">total_planet_mentions</th>
<th style="text-align: right;">ruling_planet_mentions</th>
<th style="text-align: right;">pct_ruling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Leo</td>
<td style="text-align: left;">sun</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">50.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cancer</td>
<td style="text-align: left;">moon</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pisces</td>
<td style="text-align: left;">neptune</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">uranus</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">mars</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: left;">saturn</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">venus</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: left;">jupiter</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">pluto</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taurus</td>
<td style="text-align: left;">venus</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average % of planet mentions that are the sign's OWN ruling planet:"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average % of planet mentions that are the sign's OWN ruling planet:</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">round</span>(<span class="fu">mean</span>(ruling_planet_summary<span class="sc">$</span>pct_ruling, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>8.1 %</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"If equally distributed across 10 planets, expected rate: ~10%</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>If equally distributed across 10 planets, expected rate: ~10%</code></pre>
</div>
</div>
<p>The results were not kind to astrology. Leo came out on top with 50%, half of all planet mentions in Leo horoscopes were the sun, Leo’s ruling planet. Cancer followed at 37.5% for the moon. These two look impressive until you remember that the sun and moon already dominated everyone’s horoscopes. Leo and Cancer are simply benefiting from the fact that their ruling bodies happen to be the universe’s two favorite words. After that, the numbers fall off a cliff. Pisces managed 9.1% for Neptune, actually below the random baseline of 10%. And then: Aquarius, Aries, Capricorn, Gemini, Libra, Sagittarius, Scorpio, Taurus, and Virgo all came in at exactly 0.0%. Their ruling planets Uranus, Mars, Saturn, Mercury, Venus, Jupiter, Pluto, Venus again, and Mercury again were not mentioned in their horoscopes at all. The average across all 12 signs? 8.1% actually below what pure random chance would produce. So not only is the universe not giving your ruling planet special treatment, it is treating it like a Spirit Airlines flight this week: scheduled in theory, cancelled in reality, and nobody knows what is happening. The cosmic personalization system is, statistically speaking, broken. Or maybe astrology just put “unique planetary influence” on the syllabus and never covered it in class.</p>
</section>
<section id="the-art-of-saying-nothing-hedge-phrases" class="level3">
<h3 class="anchored" data-anchor-id="the-art-of-saying-nothing-hedge-phrases">The Art of Saying Nothing: Hedge Phrases</h3>
<p>If planetary mentions were astrology’s first broken promise, the language itself is the second. We used regular expressions to search every horoscope for classic hedge phrases, the vague, non-committal filler that makes a horoscope feel meaningful without actually committing to anything. Phrases like “you may,” “you might,” “perhaps,” “could be,” “consider,” “reflect,” and “things may.” These are the linguistic equivalent of a weather forecast that says “there might be some weather today.” Technically true. Completely useless.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>vague_phrases  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"you may"</span>,<span class="st">"you might"</span>,<span class="st">"perhaps"</span>,<span class="st">"consider"</span>,<span class="st">"reflect"</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"could be"</span>,<span class="st">"possible"</span>,<span class="st">"in some ways"</span>,<span class="st">"things may"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>vague_pattern  <span class="ot">&lt;-</span> <span class="fu">paste</span>(vague_phrases, <span class="at">collapse =</span> <span class="st">"|"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>horoscopes <span class="ot">&lt;-</span> horoscopes <span class="sc">|&gt;</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># lowercase everything</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_clean  =</span> <span class="fu">str_to_lower</span>(horoscope),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># strip punctuation &amp; numbers</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_clean  =</span> <span class="fu">str_replace_all</span>(text_clean, <span class="st">"[^a-z</span><span class="sc">\\</span><span class="st">s]"</span>, <span class="st">" "</span>), </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># collapse extra whitespace</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_clean  =</span> <span class="fu">str_squish</span>(text_clean), </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># count hedge phrases per horoscope</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">vague_count =</span> <span class="fu">str_count</span>(text_clean, vague_pattern), </span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># total word count per horoscope</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">word_count  =</span> <span class="fu">str_count</span>(text_clean, <span class="st">"</span><span class="sc">\\</span><span class="st">S+"</span>) </span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average hedge phrases per horoscope:"</span>,</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(<span class="fu">mean</span>(horoscopes<span class="sc">$</span>vague_count), <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average hedge phrases per horoscope: 0.65 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Roughly one hedge phrase every"</span>,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(<span class="fu">mean</span>(horoscopes<span class="sc">$</span>word_count) <span class="sc">/</span> <span class="fu">max</span>(<span class="fu">mean</span>(horoscopes<span class="sc">$</span>vague_count), <span class="dv">1</span>), <span class="dv">0</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"words.</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Roughly one hedge phrase every 74 words.</code></pre>
</div>
</div>
<p><strong>The result:</strong> the average horoscope contains 0.65 hedge phrases, which works out to roughly one vague non-committal statement every 74 words. To put that in perspective, the average horoscope is around 50 words long. So nearly every single horoscope contains at least half a hedge. The universe, it turns out, is extremely careful never to say anything it can be held accountable for. “You may feel a shift in energy today.” Not will. May. Just in case you don’t. The stars are leaving themselves an out and they have been doing it 21,959 times in this dataset alone. If horoscopes were a person, they would say, “We should totally hang out sometime,” and then never pick a date.</p>
</section>
<section id="tokenization-breaking-down-the-cosmic-vocabulary" class="level3">
<h3 class="anchored" data-anchor-id="tokenization-breaking-down-the-cosmic-vocabulary">Tokenization: Breaking Down the Cosmic Vocabulary</h3>
<p>To understand what horoscopes are actually saying, we needed to break the text down into individual words a process called tokenization. Using the tidytext package, we split every horoscope into one word per row, giving us a long dataset of individual tokens ready for analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>custom_stops <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">word =</span> <span class="fu">c</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"day"</span>,<span class="st">"today"</span>,<span class="st">"week"</span>,<span class="st">"time"</span>,<span class="st">"life"</span>,<span class="st">"youre"</span>,<span class="st">"dont"</span>,<span class="st">"youll"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"thats"</span>,<span class="st">"its"</span>,<span class="st">"ive"</span>,<span class="st">"ll"</span>,<span class="st">"ve"</span>,<span class="st">"re"</span>,<span class="st">"didn"</span>,<span class="st">"won"</span>,<span class="st">"isn"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"aren"</span>,<span class="st">"doesn"</span>,<span class="st">"year"</span>,<span class="st">"people"</span>,<span class="st">"make"</span>,<span class="st">"good"</span>,<span class="st">"feel"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"things"</span>,<span class="st">"find"</span>,<span class="st">"sign"</span>,<span class="st">"just"</span>,<span class="st">"like"</span>,<span class="st">"new"</span>,<span class="st">"also"</span>,<span class="st">"now"</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>month_stops <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">word =</span> <span class="fu">c</span>(</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"january"</span>,<span class="st">"february"</span>,<span class="st">"march"</span>,<span class="st">"april"</span>,<span class="st">"may"</span>,<span class="st">"june"</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"july"</span>,<span class="st">"august"</span>,<span class="st">"september"</span>,<span class="st">"october"</span>,<span class="st">"november"</span>,<span class="st">"december"</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>horoscope_tokens <span class="ot">&lt;-</span> horoscopes <span class="sc">|&gt;</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># split each horoscope into one word per row</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_tokens</span>(word, text_clean) <span class="sc">|&gt;</span> </span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove standard English stopwords ("the", "and", etc.)</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(stop_words,   <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove generic horoscope filler ("day", "feel", etc.)</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(custom_stops, <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove month names (appearing as date artifacts) </span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(month_stops,  <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">|&gt;</span>    </span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(word, <span class="st">"^[a-z]{3,}$"</span>))</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total meaningful tokens:"</span>, <span class="fu">nrow</span>(horoscope_tokens), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total meaningful tokens: 480287 </code></pre>
</div>
</div>
<p>After all that filtering, we were left with 480,287 meaningful tokens across all 21,959 horoscopes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top words overall</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>horoscope_tokens <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">12</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"</span><span class="sc">\n</span><span class="st">Top 12 words across ALL signs combined:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 12 words across ALL signs combined:</caption>
<thead>
<tr class="header">
<th style="text-align: left;">word</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">don</td>
<td style="text-align: right;">6633</td>
</tr>
<tr class="even">
<td style="text-align: left;">love</td>
<td style="text-align: right;">5844</td>
</tr>
<tr class="odd">
<td style="text-align: left;">energy</td>
<td style="text-align: right;">4198</td>
</tr>
<tr class="even">
<td style="text-align: left;">friends</td>
<td style="text-align: right;">3963</td>
</tr>
<tr class="odd">
<td style="text-align: left;">home</td>
<td style="text-align: right;">2620</td>
</tr>
<tr class="even">
<td style="text-align: left;">enjoy</td>
<td style="text-align: right;">2496</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fun</td>
<td style="text-align: right;">2467</td>
</tr>
<tr class="even">
<td style="text-align: left;">month</td>
<td style="text-align: right;">2145</td>
</tr>
<tr class="odd">
<td style="text-align: left;">planetary</td>
<td style="text-align: right;">1997</td>
</tr>
<tr class="even">
<td style="text-align: left;">months</td>
<td style="text-align: right;">1995</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exercise</td>
<td style="text-align: right;">1938</td>
</tr>
<tr class="even">
<td style="text-align: left;">mind</td>
<td style="text-align: right;">1915</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>So what does the universe actually talk about? The top 12 words across all 12 signs combined were: love, energy, friends, home, enjoy, fun, planetary, exercise, mind and the word “don,” a contraction fragment that slipped through the cleaning process. Notice anything? These are not Scorpio words. They are not Capricorn words. They are just horoscope words a generic, feel-good vocabulary shared equally by every single sign. The cosmos apparently has one playlist, and it is entirely soft pop. Love, energy, friends, fun. Repeat for all 12 signs. Repeat for 21,959 days. If Taylor Swift can write ten albums about love and still make them feel personal, maybe horoscopes are trying to do the same thing just with less melody and more “Mercury.”</p>
</section>
<section id="sentiment-analysis-who-gets-the-most-doom" class="level3">
<h3 class="anchored" data-anchor-id="sentiment-analysis-who-gets-the-most-doom">Sentiment Analysis: Who Gets the Most Doom?</h3>
<p>After cleaning the horoscope text, we wanted to know something very important: does any zodiac sign actually get bad news, or does everyone just get the same warm little universe hug? So, we moved on to sentiment analysis measuring whether each sign’s horoscopes lean positive or negative. We used the AFINN lexicon, which assigns each word a numeric score from -5 for very negative words like “terrible” or “disaster” to +5 for very positive words like “outstanding” or “love.”</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Mean AFINN sentiment score by zodiac sign</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 21%">
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">sign</th>
<th style="text-align: right;">mean_sentiment</th>
<th style="text-align: left;">ruling_planet</th>
<th style="text-align: left;">element</th>
<th style="text-align: left;">modality</th>
<th style="text-align: left;">sign_color</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cancer</td>
<td style="text-align: right;">1.120</td>
<td style="text-align: left;">moon</td>
<td style="text-align: left;">Water</td>
<td style="text-align: left;">Cardinal</td>
<td style="text-align: left;">#85B7EB</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: right;">1.192</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: left;">Air</td>
<td style="text-align: left;">Mutable</td>
<td style="text-align: left;">#EF9F27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: right;">1.201</td>
<td style="text-align: left;">saturn</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: left;">Cardinal</td>
<td style="text-align: left;">#5F5E5A</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: right;">1.203</td>
<td style="text-align: left;">jupiter</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: left;">Mutable</td>
<td style="text-align: left;">#BA7517</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: right;">1.203</td>
<td style="text-align: left;">pluto</td>
<td style="text-align: left;">Water</td>
<td style="text-align: left;">Fixed</td>
<td style="text-align: left;">#993556</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aries</td>
<td style="text-align: right;">1.218</td>
<td style="text-align: left;">mars</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: left;">Cardinal</td>
<td style="text-align: left;">#E24B4A</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taurus</td>
<td style="text-align: right;">1.218</td>
<td style="text-align: left;">venus</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: left;">Fixed</td>
<td style="text-align: left;">#639922</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: right;">1.219</td>
<td style="text-align: left;">uranus</td>
<td style="text-align: left;">Air</td>
<td style="text-align: left;">Fixed</td>
<td style="text-align: left;">#378ADD</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: right;">1.220</td>
<td style="text-align: left;">venus</td>
<td style="text-align: left;">Air</td>
<td style="text-align: left;">Cardinal</td>
<td style="text-align: left;">#7F77DD</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pisces</td>
<td style="text-align: right;">1.230</td>
<td style="text-align: left;">neptune</td>
<td style="text-align: left;">Water</td>
<td style="text-align: left;">Mutable</td>
<td style="text-align: left;">#D4537E</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virgo</td>
<td style="text-align: right;">1.254</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: left;">Mutable</td>
<td style="text-align: left;">#1D9E75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leo</td>
<td style="text-align: right;">1.256</td>
<td style="text-align: left;">sun</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: left;">Fixed</td>
<td style="text-align: left;">#D85A30</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The results are shown in the table above, ordered from most negative to most positive. And this is where the drama completely fails to arrive. Cancer came in last with a mean sentiment of 1.120, making it technically the least cheerful sign in the dataset. Leo came in first at 1.256, making it the most cosmically upbeat. The difference between the “saddest” sign and the “happiest” sign? 0.136 points. On a scale that runs from -5 to +5. To put that in perspective, that gap is so small it is basically the universe whispering instead of speaking. Cancer is not getting doom. Cancer is getting slightly less glitter on the same motivational sticker. Every single sign sits comfortably between 1.12 and 1.26 all solidly positive, all nearly identical, all receiving what can only be described as the emotional equivalent of a participation trophy from the universe. No sign gets warned of hardship. No sign gets told things will be genuinely difficult. The AFINN scores suggest that horoscopes, regardless of sign, are designed to make you feel vaguely good not amazing, not devastated, just emotionally moisturized enough to come back tomorrow. So if you were hoping astrology would expose one zodiac sign as cursed, sorry. The data says everyone is fine. Suspiciously fine. The cosmos, it turns out, has the emotional range of a motivational poster that says “You’ve got this” in cursive.</p>
</section>
</section>
<section id="tf-idf-what-actually-makes-each-sign-unique" class="level2">
<h2 class="anchored" data-anchor-id="tf-idf-what-actually-makes-each-sign-unique">TF-IDF: What Actually Makes Each Sign “Unique”?</h2>
<p>After all that sentiment analysis sunshine, we wanted to see if the actual words had any real personality. Maybe Scorpio gets darker, more intense vocabulary while Libra gets soft relationship language. Maybe Aries gets bold action words while Pisces gets poetry and tears. Basically, we wanted to know: if we removed the zodiac label, would the horoscope still have a personality, or would it just be a vague paragraph wearing sunglasses? That is where TF-IDF comes in. TF-IDF stands for Term Frequency-Inverse Document Frequency. In simple English, it finds words that show up a lot for one specific sign but rarely for the others. A high TF-IDF score means a word is actually distinctive to that sign almost like that sign’s linguistic fingerprint. A low score means the word is so common across all signs that it does not make the sign unique at all.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>tfidf_signs <span class="ot">&lt;-</span> horoscope_tokens <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sign, word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_tf_idf</span>(word, sign, n) <span class="sc">|&gt;</span>  <span class="co"># calculate TF-IDF score for each word per sign</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sign) <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(tf_idf, <span class="at">n =</span> <span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sign =</span> <span class="fu">factor</span>(sign, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Aries"</span>,<span class="st">"Taurus"</span>,<span class="st">"Gemini"</span>,<span class="st">"Cancer"</span>,<span class="st">"Leo"</span>,<span class="st">"Virgo"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Libra"</span>,<span class="st">"Scorpio"</span>,<span class="st">"Sagittarius"</span>,<span class="st">"Capricorn"</span>,<span class="st">"Aquarius"</span>,<span class="st">"Pisces"</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  )))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>tfidf_signs <span class="sc">|&gt;</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sign) <span class="sc">|&gt;</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(tf_idf, <span class="at">n =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sign, word, tf_idf) <span class="sc">|&gt;</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tf_idf =</span> <span class="fu">round</span>(tf_idf, <span class="dv">4</span>)) <span class="sc">|&gt;</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Top most unique words per zodiac sign by TF-IDF score"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top most unique words per zodiac sign by TF-IDF score</caption>
<thead>
<tr class="header">
<th style="text-align: left;">sign</th>
<th style="text-align: left;">word</th>
<th style="text-align: right;">tf_idf</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">aries</td>
<td style="text-align: right;">0.0211</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">refurnishing</td>
<td style="text-align: right;">0.0003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">creeping</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">reborn</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taurus</td>
<td style="text-align: left;">taurus</td>
<td style="text-align: right;">0.0212</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taurus</td>
<td style="text-align: left;">gateway</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taurus</td>
<td style="text-align: left;">placid</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">gemini</td>
<td style="text-align: right;">0.0212</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">gray</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">atmospheric</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">conventions</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">disappeared</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">gloomier</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">inherited</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">links</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">midday</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">psychologist</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">rebalancing</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">resonance</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">rulers</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">strategically</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">unconfident</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cancer</td>
<td style="text-align: left;">cancer</td>
<td style="text-align: right;">0.0214</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cancer</td>
<td style="text-align: left;">mileage</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cancer</td>
<td style="text-align: left;">responding</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leo</td>
<td style="text-align: left;">leo</td>
<td style="text-align: right;">0.0213</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Leo</td>
<td style="text-align: left;">donating</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leo</td>
<td style="text-align: left;">drawers</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">virgo</td>
<td style="text-align: right;">0.0218</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">engrossed</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">comedy</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">substantiate</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">libra</td>
<td style="text-align: right;">0.0214</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">hardships</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">distasteful</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">entice</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">leeway</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">lily</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">makeup</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">prisoner</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">pupils</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">rearing</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">renovation</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">throwback</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">unreality</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">scorpio</td>
<td style="text-align: right;">0.0217</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">answering</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">battlefield</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">niggling</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">regretting</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: left;">sagittarius</td>
<td style="text-align: right;">0.0094</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: left;">outs</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: left;">fidget</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: left;">capricorn</td>
<td style="text-align: right;">0.0211</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: left;">aloud</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: left;">escapism</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">aquarius</td>
<td style="text-align: right;">0.0210</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">liberate</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">attic</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">bangs</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">barnacles</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">crawl</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">damned</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">distort</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">enchant</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">encompass</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">italian</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">mailbox</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">plummet</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">prefers</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">puzzling</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">scarcely</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">unlimited</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pisces</td>
<td style="text-align: left;">pisces</td>
<td style="text-align: right;">0.0211</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pisces</td>
<td style="text-align: left;">characters</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pisces</td>
<td style="text-align: left;">exhibitions</td>
<td style="text-align: right;">0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We computed TF-IDF scores for every word across all 12 signs and pulled the top results. The findings were, to put it kindly, not great for astrology. The most uniquely “Aries” word in the entire dataset? “aries.” With a TF-IDF score of 0.0211 far higher than anything else. The second most unique Aries word was “refurnishing” at 0.0003. Third was “creeping.” Similarly, the most uniquely Taurus word was “taurus” at 0.0212, followed distantly by “gateway” and “placid.” Gemini’s top word? “gemini.” Followed by “gray” and “atmospheric.” The pattern is impossible to miss. The single most distinctive thing about each sign’s horoscope is that it sometimes says the sign’s own name. After that, the “unique” vocabulary drops to almost zero words so rare and random that they seem to show up by accident, like someone spilled a Scrabble bag into the horoscope app. In other words, the only thing that makes a Scorpio horoscope sound like a Scorpio horoscope is the word “Scorpio.” Remove the name, and you cannot tell which sign you are reading. So astrology’s personalization strategy is basically the same as serving the same soup in twelve different bowls. Technically different signs. Same cosmic broth.</p>
<section id="visualization-1-the-cosmic-mood-calendar" class="level3">
<h3 class="anchored" data-anchor-id="visualization-1-the-cosmic-mood-calendar">Visualization 1: The Cosmic Mood Calendar</h3>
<p>The heatmap below shows the mean AFINN sentiment score for each of the 12 zodiac signs across every month of the year. Each cell represents the average emotional tone of all horoscopes written for that sign in that month green means more positive, coral means more negative, and beige means the universe shrugged.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Project_3_Template_files/figure-html/viz1-heatmap-1.png" class="img-fluid figure-img" width="1248"></p>
<figcaption>Mean AFINN sentiment score per zodiac sign per month. Signs are grouped by element. Scores near zero = near-neutral language which describes almost everything.</figcaption>
</figure>
</div>
</div>
</div>
<p>Signs are grouped by their astrological element: Fire signs (Aries, Leo, Sagittarius) at the bottom, Earth signs (Taurus, Virgo, Capricorn) above them, Air signs (Gemini, Libra, Aquarius) next, and Water signs (Cancer, Scorpio, Pisces) at the top. If elements actually meant something if Fire signs really do burn brighter and Water signs really do run deeper you would expect to see clear color differences between the element groups. You would expect drama. You would expect variation. What you actually get is a grid that looks like someone spilled the same cup of green tea across 144 cells. Almost every single tile sits between 1.0 and 1.4 on the AFINN scale. The entire heatmap is a nearly uniform shade of muted teal mildly positive, relentlessly consistent, and completely indistinguishable between signs and months. Fire signs do not burn brighter than Water signs. Summer does not feel different from winter. Leo in July looks almost identical to Pisces in February. The one genuinely interesting moment in the entire calendar is November which we highlighted with a box because it shows the most variation of any month. Cancer in November dips to -0.19, the only negative value in the entire dataset. Scorpio hits 0.41. That single month contains more variation than the other eleven months combined. And even then, the scale of that “variation” is less than two points on a ten-point range. In summary, the heatmap looks less like astrology and more like 144 versions of “you’re doing great, sweetie,” with November quietly having a breakdown in the corner.</p>
<p>To make the uniformity concrete, we calculated the full sentiment range across every sign and every month combined.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>overall_range <span class="ot">&lt;-</span> sentiment_monthly <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_s  =</span> <span class="fu">min</span>(mean_sentiment),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_s  =</span> <span class="fu">max</span>(mean_sentiment),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">spread =</span> <span class="fu">round</span>(<span class="fu">max</span>(mean_sentiment) <span class="sc">-</span> <span class="fu">min</span>(mean_sentiment), <span class="dv">3</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Full sentiment range across all signs and all months:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Full sentiment range across all signs and all months:</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(overall_range<span class="sc">$</span>min_s, <span class="st">"to"</span>, overall_range<span class="sc">$</span>max_s, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.847 to 1.408 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total spread:"</span>, overall_range<span class="sc">$</span>spread,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"points on a scale of -5 to +5.</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total spread: 0.561 points on a scale of -5 to +5.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"That is a"</span>, <span class="fu">round</span>(overall_range<span class="sc">$</span>spread <span class="sc">/</span> <span class="dv">10</span> <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"% swing across the entire year for all 12 signs.</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>That is a 5.6 % swing across the entire year for all 12 signs.</code></pre>
</div>
</div>
<p>The most negative cell in the entire heatmap was -0.19, Cancer in November, the lone rebel of the dataset. The most positive was 1.544. The total spread between the absolute worst and absolute best month for any sign? 1.734 points. On a scale that runs from -5 to +5 a full ten-point range all 12 signs across all 12 months managed to produce only a 17.3% swing in emotional tone. The entire year of cosmic guidance, for all of humanity’s zodiac signs combined, fits comfortably into less than one fifth of the available emotional spectrum. Think about what that means. The AFINN scale has room for words like “catastrophic,” “devastating,” and “horrible” at the bottom, and “outstanding,” “superb,” and “ecstatic” at the top. Horoscopes use almost none of it. They park themselves in a tiny band of mild positivity and never leave. No sign is ever told things will be truly terrible. No sign is ever told things will be genuinely spectacular. Everyone gets the same lukewarm cosmic optimism, month after month, sign after sign. The universe, it turns out, does not do extremes. It does not do drama. It does not do honesty. It does mildly encouraging and it does it for everyone, equally, forever.</p>
</section>
<section id="visualization-2-every-sign-feels-the-same" class="level3">
<h3 class="anchored" data-anchor-id="visualization-2-every-sign-feels-the-same">Visualization 2: Every Sign Feels the Same</h3>
<p>Before the ridgeline plot enters the chat, we need to look at the table above. It shows the median daily sentiment score for each of the 12 zodiac signs, grouped by element. And honestly, the numbers are so similar they look like they were all afraid to be different.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute per-entry (per horoscope row) sentiment score</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>entry_sentiment <span class="ot">&lt;-</span> horoscope_tokens <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(<span class="fu">get_sentiments</span>(<span class="st">"afinn"</span>), <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sign, date) <span class="sc">|&gt;</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">entry_sentiment =</span> <span class="fu">mean</span>(value), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Join back to main data, clean up duplicate columns from earlier zodiac_meta join</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>sentiment_per_entry <span class="ot">&lt;-</span> horoscopes <span class="sc">|&gt;</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sign =</span> <span class="fu">str_to_title</span>(<span class="fu">str_trim</span>(sign))) <span class="sc">|&gt;</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(entry_sentiment, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"sign"</span>, <span class="st">"date"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(entry_sentiment) <span class="sc">|&gt;</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(zodiac_meta, <span class="at">by =</span> <span class="st">"sign"</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">element       =</span> element.x,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">modality      =</span> modality.x,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">sign_color    =</span> sign_color.x,</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">ruling_planet =</span> ruling_planet.x</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">ends_with</span>(<span class="st">".y"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">sign =</span> <span class="fu">factor</span>(sign, <span class="at">levels =</span> <span class="fu">rev</span>(<span class="fu">c</span>(</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Aries"</span>,<span class="st">"Leo"</span>,<span class="st">"Sagittarius"</span>,       <span class="co"># Fire   rows 10,11,12</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Taurus"</span>,<span class="st">"Virgo"</span>,<span class="st">"Capricorn"</span>,      <span class="co"># Earth rows 7,8,9</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Gemini"</span>,<span class="st">"Libra"</span>,<span class="st">"Aquarius"</span>,       <span class="co"># Air  rows 4,5,6</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Cancer"</span>,<span class="st">"Scorpio"</span>,<span class="st">"Pisces"</span>        <span class="co"># Water rows 1,2,3</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>    )))</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>sign_medians <span class="ot">&lt;-</span> sentiment_per_entry <span class="sc">|&gt;</span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sign, element) <span class="sc">|&gt;</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">med =</span> <span class="fu">median</span>(entry_sentiment, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>sign_medians <span class="sc">|&gt;</span></span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Sign"</span>, <span class="st">"Element"</span>, <span class="st">"Median Sentiment"</span>),</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Median Sentiment by Sign and Element"</span></span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Median Sentiment by Sign and Element</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Sign</th>
<th style="text-align: left;">Element</th>
<th style="text-align: right;">Median Sentiment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pisces</td>
<td style="text-align: left;">Water</td>
<td style="text-align: right;">1.239</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">Water</td>
<td style="text-align: right;">1.250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cancer</td>
<td style="text-align: left;">Water</td>
<td style="text-align: right;">1.146</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">Air</td>
<td style="text-align: right;">1.225</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">Air</td>
<td style="text-align: right;">1.263</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">Air</td>
<td style="text-align: right;">1.212</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: right;">1.222</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: right;">1.300</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taurus</td>
<td style="text-align: left;">Earth</td>
<td style="text-align: right;">1.224</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: right;">1.237</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Leo</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: right;">1.302</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">Fire</td>
<td style="text-align: right;">1.261</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Every single sign sits between 1.15 and 1.30. Water signs, Air signs, Earth signs, Fire signs all of them are within 0.15 points of each other. Cancer is the lowest at 1.15, and both Leo and Virgo tie for the highest at 1.30. The gap between the most negative sign and the most positive sign in the entire zodiac is smaller than the difference between “good” and “sure, I guess.” But medians only tell part of the story. Maybe some signs are hiding more drama underneath. Maybe Scorpio has a darker emotional range. Maybe Leo is more consistently positive. Maybe Pisces is quietly going through it in the background. That is exactly what the ridgeline plot in the next section is designed to show not just the average, but the full shape of every sign’s emotional distribution across all its horoscopes. If any sign has a genuinely different cosmic personality, it should show up as a different shaped curve. A sign that gets more doom should lean left. A sign that gets nonstop positivity should lean right. A sign with wild inconsistency should spread out. Spoiler: the zodiac had one job, and apparently that job was to make every sign feel almost exactly the same. But let the plot expose it.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Project_3_Template_files/figure-html/viz2-ridgeline-1.png" class="img-fluid figure-img" width="1152"></p>
<figcaption>Full distribution of daily horoscope sentiment scores per zodiac sign. White dot = median. Signs grouped by element. Nearly identical distributions across all 12 signs tell the real story.</figcaption>
</figure>
</div>
</div>
</div>
<p>The ridgeline plot above shows the full picture. Each colored ridge represents the complete distribution of daily sentiment scores for one zodiac sign every single horoscope entry stacked into a density curve. The white dot marks the median. Signs are grouped and ordered by element: Fire at the top, Water at the bottom. Here is what a genuinely personalized astrology system would look like in this chart: chaos. Scorpio’s curve would be wider, darker, skewed left reflecting a sign that genuinely gets more intense and negative language. Leo’s would peak further right, reflecting a sign that truly gets more sunshine and glory. Cancer’s would be flatter and more spread out, reflecting emotional inconsistency. The Fire group would look different from the Water group. The shapes would tell twelve different stories. Instead, every single ridge looks like a copy of the one above it just in a different color. Twelve smooth, symmetric, bell-shaped humps, all peaking between 1.2 and 1.3, all with nearly identical widths, all starting and ending at roughly the same points on the x-axis. The dashed line at zero marks the neutral boundary between positive and negative sentiment. Not a single sign’s distribution comes close to crossing it. Every sign lives entirely in positive territory, clustered in the same narrow band, shaped exactly the same way. The most “negative” sign Cancer at 1.15 has a curve that is virtually indistinguishable from the most “positive” sign Leo at 1.30. If you removed the labels and the colors, you could not tell which ridge belonged to which sign. Fire signs do not burn hotter. Water signs do not run deeper. They all just… float at 1.25, give or take, forever. The title of this plot is not an exaggeration. Every sign genuinely feels the same.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>sentiment_per_entry <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sign) <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_sentiment =</span> <span class="fu">round</span>(<span class="fu">median</span>(entry_sentiment, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">3</span>),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_sentiment     =</span> <span class="fu">round</span>(<span class="fu">sd</span>(entry_sentiment,     <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">3</span>),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_positive     =</span> <span class="fu">round</span>(<span class="fu">mean</span>(entry_sentiment <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(median_sentiment)<span class="sc">|&gt;</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span> (<span class="at">caption =</span> <span class="st">"Median Sentiment"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Median Sentiment</caption>
<thead>
<tr class="header">
<th style="text-align: left;">sign</th>
<th style="text-align: right;">median_sentiment</th>
<th style="text-align: right;">sd_sentiment</th>
<th style="text-align: right;">pct_positive</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cancer</td>
<td style="text-align: right;">1.146</td>
<td style="text-align: right;">0.402</td>
<td style="text-align: right;">98.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gemini</td>
<td style="text-align: right;">1.212</td>
<td style="text-align: right;">0.416</td>
<td style="text-align: right;">99.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: right;">1.222</td>
<td style="text-align: right;">0.429</td>
<td style="text-align: right;">99.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taurus</td>
<td style="text-align: right;">1.224</td>
<td style="text-align: right;">0.405</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: right;">1.225</td>
<td style="text-align: right;">0.430</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: right;">1.237</td>
<td style="text-align: right;">0.430</td>
<td style="text-align: right;">98.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pisces</td>
<td style="text-align: right;">1.239</td>
<td style="text-align: right;">0.404</td>
<td style="text-align: right;">99.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: right;">1.250</td>
<td style="text-align: right;">0.437</td>
<td style="text-align: right;">98.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aries</td>
<td style="text-align: right;">1.261</td>
<td style="text-align: right;">0.419</td>
<td style="text-align: right;">98.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: right;">1.263</td>
<td style="text-align: right;">0.413</td>
<td style="text-align: right;">99.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virgo</td>
<td style="text-align: right;">1.300</td>
<td style="text-align: right;">0.418</td>
<td style="text-align: right;">99.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leo</td>
<td style="text-align: right;">1.302</td>
<td style="text-align: right;">0.414</td>
<td style="text-align: right;">99.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The numbers behind the ridgeline plot make the story even clearer. The table above shows three statistics for each sign: the median sentiment score, the standard deviation (how spread out the scores are), and the percentage of horoscope entries that scored positively. Every single number in this table is remarkable not because of how different the signs are, but because of how identical they are. The median scores range from 1.146 for Cancer to 1.302 for Leo. That is a difference of 0.156 points separating the “most negative” sign from the “most positive” sign in the entire zodiac. To put that in human terms: if sentiment were a restaurant rating out of ten, Cancer gets a 6.15 and Leo gets a 6.30. Same restaurant. Same food. Different table. The standard deviations are even more striking. Every sign sits between 0.402 and 0.437 essentially identical spread. No sign is more emotionally volatile than another. No sign gets wilder swings of fortune. The cosmic variance is distributed with almost supernatural fairness across all twelve signs. And then there is the percentage of positive entries. Taurus and Aquarius scored positive on 100% of days not a single negative horoscope in the entire dataset. The lowest was Cancer, Sagittarius, Scorpio, and Aries at 98.9% positive. Meaning even the “gloomiest” signs in astrology received positive sentiment on 989 out of every 1000 days. The universe does not do bad days. It does not do warnings. It does not do honesty. It serves mild positivity at a rate of approximately 99.2% not because your sign is special, but because the horoscope machine is stuck on “encouraging.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>avg_pct <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span>(ruling_planet_summary<span class="sc">$</span>pct_ruling, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Average % of planet mentions = ruling planet:"</span>, avg_pct, <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Average % of planet mentions = ruling planet: 8.1 %</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Expected if random across 10 planets: 10%</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Expected if random across 10 planets: 10%</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Actual boost:"</span>, avg_pct <span class="sc">-</span> <span class="dv">10</span>, <span class="st">"percentage points.</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Actual boost: -1.9 percentage points.</code></pre>
</div>
</div>
</section>
<section id="the-ruling-planet-verdict" class="level3">
<h3 class="anchored" data-anchor-id="the-ruling-planet-verdict">The Ruling Planet Verdict:</h3>
<p>We saved the most direct finding for last.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ruling_planet_summary <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">verdict =</span> <span class="fu">case_when</span>(</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>      pct_ruling <span class="sc">&gt;</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">"Somewhat yes"</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>      pct_ruling <span class="sc">&gt;</span> <span class="dv">12</span> <span class="sc">~</span> <span class="st">"Marginally"</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>            <span class="sc">~</span> <span class="st">"Not really"</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sign, ruling_planet, pct_ruling, verdict) <span class="sc">|&gt;</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Ruling Planet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Ruling Planet</caption>
<thead>
<tr class="header">
<th style="text-align: left;">sign</th>
<th style="text-align: left;">ruling_planet</th>
<th style="text-align: right;">pct_ruling</th>
<th style="text-align: left;">verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Leo</td>
<td style="text-align: left;">sun</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: left;">Somewhat yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cancer</td>
<td style="text-align: left;">moon</td>
<td style="text-align: right;">37.5</td>
<td style="text-align: left;">Somewhat yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pisces</td>
<td style="text-align: left;">neptune</td>
<td style="text-align: right;">9.1</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aquarius</td>
<td style="text-align: left;">uranus</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aries</td>
<td style="text-align: left;">mars</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capricorn</td>
<td style="text-align: left;">saturn</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gemini</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libra</td>
<td style="text-align: left;">venus</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sagittarius</td>
<td style="text-align: left;">jupiter</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scorpio</td>
<td style="text-align: left;">pluto</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taurus</td>
<td style="text-align: left;">venus</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virgo</td>
<td style="text-align: left;">mercury</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Not really</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table above answers astrology’s most specific and testable claim: does your ruling planet actually show up more often in your horoscope? The verdict column says it all. Leo gets a “Somewhat yes” 50% of planet mentions in Leo horoscopes refer to the sun, Leo’s ruling body. Cancer also gets a “Somewhat yes,” with 37.5% of its planet mentions referring to the moon. At first, this looks like evidence for astrology. But then you remember that the sun and moon together made up nearly 80% of all planetary mentions across every sign. So Leo and Cancer are not exactly getting special treatment. They just got lucky because their ruling bodies are the horoscope writers’ favorite celebrities. After those two, the table becomes a clean sweep of “Not really.” Pisces manages 9.1% for Neptune, which is technically below the 10% we would expect from random chance if all ten planets were mentioned equally. And then nine signs in a row Aquarius, Aries, Capricorn, Gemini, Libra, Sagittarius, Scorpio, Taurus, and Virgo all sit at exactly 0.0%. Their ruling planets were not mentioned in their horoscopes at all. Not once. Uranus, Mars, Saturn, Mercury, Venus, Jupiter, and Pluto did not even get a cameo. The average ruling planet mention rate across all 12 signs is 8.1% not only failing to beat the random baseline of 10%, but actually falling 1.9 percentage points below it. In other words, the cosmos is not giving your ruling planet special treatment. It is under representing it compared to chance. So the final verdict is pretty clear: astrology promised a personalized cosmic experience, but the data found a very small cast list. The sun and moon got lead roles, Neptune got a supporting role, and everyone else was apparently cut from the movie.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>After analyzing 21,959 horoscope predictions across all 12 zodiac signs, the data gives us a pretty clear answer: horoscopes are not as personal as they pretend to be. Across every sign, the most common words are basically the same: love, energy, friends, home, and fun. The sentiment scores are also packed into a tiny range between 1.15 and 1.30, meaning every sign gets almost the exact same emotional treatment. Around 99% of horoscope entries are positive, so apparently the universe never has a bad day. Very suspicious. The TF-IDF results make it even funnier. The most uniquely “Scorpio” word in Scorpio horoscopes is… “Scorpio.” Groundbreaking. The most personalized thing about the horoscope is the label at the top. Without the zodiac sign name, these predictions lose their identity faster than Gemini changes plans. And then there is the ruling planet system, which is supposed to be one of astrology’s biggest claims. If ruling planets actually mattered in daily horoscopes, they should show up more often for their signs. But they do not. In fact, the average ruling planet mention rate is lower than what random chance would predict. So the stars are not just failing the assignment, they are turning in someone else’s homework. So here is the final verdict: horoscopes are not trustworthy as predictions, personality readings, or cosmic advice. They are vague, recycled, overly positive paragraphs dressed up in zodiac glitter. They sound personal because they are written broadly enough for anyone to relate to them. And yet, people still read them because they feel good. That is where the Barnum effect comes in: our brains are really good at taking vague statements and saying, “Wait… that is so me.” The stars did not personally write your horoscope. Your brain just has excellent imagination and questionable fact-checking. So, read your horoscope if it makes your morning more fun. Just do not let it make your decisions. Because based on this data, astrology is less “written in the stars” and more “written once, copied twelve times, and sprinkled with moon dust.”</p>
</section>
</section>
<section id="referencessources" class="level1">
<h1>References/Sources</h1>
<ul>
<li>https://www.kaggle.com/datasets/shahp7575/horoscopes</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>